name: OpenSSF Scorecard

on:
  push:
  pull_request:
  schedule:
    - cron: '30 1 * * *'  # Daily at 1:30 UTC
  workflow_dispatch:       # Manual run support

jobs:
  scorecard:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Run Scorecard analysis"
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload Scorecard results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
